// components/smartquote/order-panel.tsx
'use client';
import { useState } from 'react';
import { Check, ClipboardCheck, Printer, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from '@/components/ui/table';
import type { SmartQuoteApi } from '@/lib/smartquote/api';
import type {
  PurchaseOrder,
  PurchaseRequest,
  Quotation,
  Simulation,
} from '@/lib/smartquote/types';
import { date, money, score, total } from '@/lib/smartquote/domain';
import { Choice, Empty, Field, Status } from './common';
import type { Action } from './request-detail';
export function OrderPanel({
  api,
  request,
  quotes,
  simulation,
  order,
  manager,
  busy,
  action,
  onOrder,
  refresh,
}: {
  api: SmartQuoteApi;
  request: PurchaseRequest;
  quotes: Quotation[];
  simulation: Simulation | null;
  order: PurchaseOrder | null;
  manager: boolean;
  busy: boolean;
  action: Action;
  onOrder: (order: PurchaseOrder) => void;
  refresh: () => Promise<void>;
}) {
  const [chosen, setChosen] = useState('');
  const [destination, setDestination] = useState('');
  const [conditions, setConditions] = useState('');
  const [confirmed, setConfirmed] = useState(false);
  const quoteId = chosen || simulation?.recommendation?.quotationId || '';
  const quote = quotes.find((q) => q.quotationId === quoteId);
  if (!manager)
    return (
      <Empty title="Revisión del jefe de compras">
        La aprobación, generación y consulta de órdenes está restringida al jefe
        de compras por los permisos actuales de la API.
      </Empty>
    );
  if (order)
    return (
      <>
        <div className="section-heading no-print">
          <div>
            <h2>Orden de compra</h2>
            <p className="muted">
              La decisión y los datos aprobados quedaron registrados.
            </p>
          </div>
          <Button variant="outline" onClick={() => window.print()}>
            <Printer />
            Imprimir
          </Button>
        </div>
        <article className="panel order-document">
          <header>
            <div>
              <span className="eyebrow">SMARTQUOTE · ORDEN DE COMPRA</span>
              <h2>{order.orderNumber}</h2>
            </div>
            <Status value={order.status} />
          </header>
          <div className="form-grid">
            <div>
              <span className="muted">Proveedor</span>
              <h3>{order.supplierBusinessName}</h3>
              <p>Identificación fiscal: {order.supplierTaxIdentifier}</p>
            </div>
            <div>
              <span className="muted">Entrega</span>
              <h3>{order.deliveryDestination}</h3>
              <p>
                {order.deliveryConditions} · {order.deliveryLeadTimeDays} días
              </p>
            </div>
          </div>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Descripción</TableHead>
                <TableHead>Cantidad</TableHead>
                <TableHead>Precio unitario</TableHead>
                <TableHead>Importe</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {order.lines.map((l) => (
                <TableRow key={l.lineId}>
                  <TableCell>{l.description}</TableCell>
                  <TableCell>
                    {l.quantity} {l.unitOfMeasure}
                  </TableCell>
                  <TableCell>{money(l.unitPrice, order.currency)}</TableCell>
                  <TableCell>
                    {money(l.quantity * l.unitPrice, order.currency)}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          <div className="order-total">
            <span>Total de la orden</span>
            <strong>{money(order.total, order.currency)}</strong>
          </div>
          <footer>
            <span>
              <ShieldCheck />
              Aprobada: {date(order.approvedAt, true)}
            </span>
            <small className="id-value">Responsable: {order.approvedBy}</small>
            <small className="id-value">
              Simulación: {order.simulationRunId}
            </small>
          </footer>
        </article>
        {['Evaluation', 'Approved'].includes(request.status) && (
          <div className="actions no-print">
            <p className="muted">
              La orden existe. Registra ahora el avance final de la solicitud.
            </p>
            <Button
              disabled={busy}
              onClick={() =>
                action(async () => {
                  let current = await api.request(request.requestId);
                  if (current.status === 'Evaluation') {
                    await api.changeStatus(
                      current,
                      'Approved',
                      `Orden ${order.orderNumber} aprobada.`,
                    );
                    current = await api.request(current.requestId);
                  }
                  if (current.status === 'Approved')
                    await api.changeStatus(
                      current,
                      'Ordered',
                      `Orden ${order.orderNumber} emitida.`,
                    );
                  await refresh();
                }, 'Solicitud actualizada a orden emitida.')
              }
            >
              <Check />
              Marcar orden emitida
            </Button>
          </div>
        )}
      </>
    );
  if (!simulation)
    return (
      <Empty title="Aún no hay una decisión de compra">
        Ejecuta una comparación y revisa sus resultados antes de generar la
        orden.
      </Empty>
    );
  const eligible = simulation.evaluations.filter((e) => e.isEligible);
  return (
    <>
      <div className="section-heading">
        <div>
          <h2>Revisar y aprobar compra</h2>
          <p className="muted">
            La orden se generará con los datos de la cotización seleccionada.
          </p>
        </div>
        <ShieldCheck className="text-primary" />
      </div>
      {!simulation.isCurrent && (
        <div className="warning-notice">
          El resultado está desactualizado. Vuelve a ejecutar la comparación.
        </div>
      )}
      {!eligible.length ? (
        <Empty title="No hay ofertas elegibles" />
      ) : (
        <form
          onSubmit={(e) => {
            e.preventDefault();
            void action(async () => {
              const latest = await api.currentSimulation(
                request.requestId,
                simulation.simulationRunId,
              );
              if (!latest.isCurrent)
                throw new Error(
                  'La simulación ya no está vigente. Vuelve a ejecutar la comparación.',
                );
              const created = await api.approve(
                simulation.simulationRunId,
                quoteId,
                conditions,
                destination,
              );
              onOrder(created);
            }, 'Orden generada y aprobada.');
          }}
        >
          <fieldset disabled={busy || !simulation.isCurrent}>
            <section className="panel">
              <Field label="Proveedor seleccionado">
                <Choice
                  label="Proveedor seleccionado"
                  value={quoteId}
                  onChange={(v) => {
                    setChosen(v);
                    setConfirmed(false);
                  }}
                  options={Object.fromEntries(
                    eligible.map((e) => [
                      e.quotationId,
                      `${quotes.find((q) => q.quotationId === e.quotationId)?.supplierBusinessName ?? e.quotationId} · ${score(e.totalScore)} puntos`,
                    ]),
                  )}
                />
              </Field>
              {quote && (
                <div className="quote-summary">
                  <div>
                    <span>Total</span>
                    <strong>
                      {money(total(quote), quote.currency ?? 'PEN')}
                    </strong>
                  </div>
                  <div>
                    <span>Entrega</span>
                    <strong>{quote.deliveryLeadTimeDays} días</strong>
                  </div>
                </div>
              )}
              <Field label="Destino de entrega">
                <Input
                  required
                  value={destination}
                  onChange={(e) => setDestination(e.target.value)}
                  placeholder="Sede, almacén y dirección"
                />
              </Field>
              <Field label="Condiciones de entrega">
                <Textarea
                  required
                  value={conditions}
                  onChange={(e) => setConditions(e.target.value)}
                  placeholder="Horario, recepción y condiciones acordadas"
                />
              </Field>
              <label className="approval-check" htmlFor="approve-order">
                <Checkbox
                  id="approve-order"
                  checked={confirmed}
                  onCheckedChange={(v) => setConfirmed(Boolean(v))}
                />
                <span>
                  He revisado la oferta y autorizo generar esta orden de compra.
                </span>
              </label>
              <div className="actions">
                <span className="muted">
                  Esta acción registra una aprobación real.
                </span>
                <Button
                  type="submit"
                  disabled={
                    !confirmed || !quoteId || busy || !simulation.isCurrent
                  }
                >
                  <ClipboardCheck />
                  Aprobar y generar orden
                </Button>
              </div>
            </section>
          </fieldset>
        </form>
      )}
    </>
  );
}

// src/purchase-ordering/presentation/order-panel.vue
<script setup>
import { ref, computed, watch } from "vue";
import { useI18n } from "vue-i18n";
import Button from "primevue/button";
import InputText from "primevue/inputtext";
import Textarea from "primevue/textarea";
import Select from "primevue/select";
import Checkbox from "primevue/checkbox";
import Field from "../../shared/presentation/components/form-field.vue";
import Status from "../../shared/presentation/components/status-chip.vue";
import { useWorkspace } from "../../shared/presentation/use-workspace.js";
import { useFormat } from "../../shared/presentation/format.js";
const props = defineProps({
  request: { type: Object, required: true },
  quotes: { type: Array, required: true },
  simulation: { type: Object, default: null },
  order: { type: Object, default: null },
  busy: Boolean,
  execute: { type: Function, required: true },
  refresh: { type: Function, required: true },
});
const emit = defineEmits(["order"]);
const { t } = useI18n(),
  format = useFormat(),
  { services, session } = useWorkspace();
const chosen = ref(""),
  destination = ref(""),
  conditions = ref(""),
  confirmed = ref(false);
const eligible = computed(
  () =>
    props.simulation?.evaluations
      .filter((e) => e.isEligible)
      .map((e) => ({
        value: e.quotationId,
        label:
          props.quotes.find((q) => q.quotationId === e.quotationId)
            ?.supplierBusinessName || e.quotationId,
      })) ?? [],
);
const quoteId = computed(
  () => chosen.value || props.simulation?.recommendation?.quotationId || "",
);
const quote = computed(() =>
  props.quotes.find((q) => q.quotationId === quoteId.value),
);
watch(
  [chosen, destination, conditions, () => props.simulation?.simulationRunId],
  () => {
    confirmed.value = false;
  },
);
async function approve() {
  await props.execute(async () => {
    const order = await services.value.orders.approve(
      props.request.requestId,
      props.simulation.simulationRunId,
      quoteId.value,
      conditions.value,
      destination.value,
    );
    emit("order", order);
    confirmed.value = false;
  }, t("saved"));
}
async function markOrdered() {
  await props.execute(async () => {
    let current = await services.value.requests.get(props.request.requestId);
    if (current.status === "Evaluation") {
      await services.value.requests.changeStatus(
        current,
        "Approved",
        props.order.orderNumber,
      );
      current = await services.value.requests.get(current.requestId);
    }
    if (current.status === "Approved")
      await services.value.requests.changeStatus(
        current,
        "Ordered",
        props.order.orderNumber,
      );
    await props.refresh();
  }, t("saved"));
}
function print() {
  window.print();
}
</script>
<template>
  <p v-if="!session.manager" class="empty-state">{{ t("managerOnly") }}</p>
  <template v-else-if="order"
    ><div class="section-heading no-print">
      <h2>{{ t("purchaseOrder") }}</h2>
      <Button :label="t('print')" icon="pi pi-print" outlined @click="print" />
    </div>
    <article class="panel order-document">
      <header>
        <div>
          <span class="eyebrow">SMARTQUOTE · {{ t("purchaseOrder") }}</span>
          <h2>{{ order.orderNumber }}</h2>
        </div>
        <Status :value="order.status" />
      </header>
      <div class="form-grid">
        <div>
          <small class="muted">{{ t("supplier") }}</small>
          <h3>{{ order.supplierBusinessName }}</h3>
          <p>{{ t("taxId") }}: {{ order.supplierTaxIdentifier }}</p>
        </div>
        <div>
          <small class="muted">{{ t("deliveryDestination") }}</small>
          <h3>{{ order.deliveryDestination }}</h3>
          <p>{{ order.deliveryConditions }}</p>
          <p>{{ t("deliveryDays") }}: {{ order.deliveryLeadTimeDays }}</p>
        </div>
      </div>
      <div class="table-scroll">
        <table>
          <thead>
            <tr>
              <th>{{ t("description") }}</th>
              <th>{{ t("quantity") }}</th>
              <th>{{ t("unitPrice") }}</th>
              <th>{{ t("total") }}</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="line in order.lines" :key="line.lineId">
              <td>{{ line.description }}</td>
              <td>{{ line.quantity }} {{ line.unitOfMeasure }}</td>
              <td>{{ format.money(line.unitPrice, order.currency) }}</td>
              <td>
                {{
                  format.money(line.quantity * line.unitPrice, order.currency)
                }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="order-total">
        {{ t("total")
        }}<strong>{{ format.money(order.total, order.currency) }}</strong>
      </div>
      <footer>
        <span>{{ t("approvedBy") }}: {{ order.approvedBy }}</span
        ><span
          >{{ t("approvedAt") }}:
          {{ format.date(order.approvedAt, true) }}</span
        ><span class="identifier">{{ order.purchaseOrderId }}</span>
      </footer>
    </article>
    <Button
      v-if="['Evaluation', 'Approved'].includes(request.status)"
      class="no-print"
      :label="t('markOrdered')"
      icon="pi pi-check"
      :disabled="busy"
      @click="markOrdered"
  /></template>
  <form
    v-else-if="simulation?.isCurrent && eligible.length"
    class="panel stack"
    @submit.prevent="approve"
  >
    <h2>{{ t("purchaseOrder") }}</h2>
    <Field :label="t('chooseSupplier')" v-slot="{ id }"
      ><Select
        :input-id="id"
        :aria-label="t('chooseSupplier')"
        :model-value="quoteId"
        @update:model-value="(value) => (chosen = value)"
        :options="eligible"
        option-label="label"
        option-value="value"
        :disabled="busy"
    /></Field>
    <div v-if="quote" class="quote-summary">
      <strong>{{ quote.supplierBusinessName }}</strong
      ><span>{{ format.money(quote.total, quote.currency) }}</span>
    </div>
    <Field :label="t('deliveryDestination')" v-slot="{ id }"
      ><InputText
        :id="id"
        v-model="destination"
        required
        :disabled="busy" /></Field
    ><Field :label="t('deliveryConditions')" v-slot="{ id }"
      ><Textarea
        :id="id"
        v-model="conditions"
        rows="3"
        required
        :disabled="busy" /></Field
    ><label for="approve-order" class="check-label"
      ><Checkbox
        input-id="approve-order"
        v-model="confirmed"
        binary
        :disabled="busy"
      />{{ t("approvalCheck") }}</label
    >
    <p class="help-text">{{ t("approvalHelp") }}</p>
    <Button
      type="submit"
      :label="t('approveOrder')"
      icon="pi pi-check-circle"
      :disabled="busy || !confirmed || !quoteId"
    />
  </form>
  <p v-else class="empty-state">{{ t("orderMissing") }}</p>
</template>
