// src/supply-requests/presentation/pages/request-detail.vue
<script setup>
import { ref, onMounted, onUnmounted } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import Button from "primevue/button";
import Select from "primevue/select";
import Textarea from "primevue/textarea";
import Dialog from "primevue/dialog";
import Tabs from "primevue/tabs";
import TabList from "primevue/tablist";
import Tab from "primevue/tab";
import TabPanels from "primevue/tabpanels";
import TabPanel from "primevue/tabpanel";
import Field from "../../../shared/presentation/components/form-field.vue";
import Status from "../../../shared/presentation/components/status-chip.vue";
import Feedback from "../../../shared/presentation/components/feedback-notice.vue";
import {
  useWorkspace,
  useFeedback,
} from "../../../shared/presentation/use-workspace.js";
import { useFormat } from "../../../shared/presentation/format.js";
import { optional } from "../../../shared/application/optional.js";
import QuotationPanel from "../../../quotation-intake/presentation/quotation-panel.vue";
import ComparisonPanel from "../../../evaluation-simulation/presentation/comparison-panel.vue";
import OrderPanel from "../../../purchase-ordering/presentation/order-panel.vue";
const { t } = useI18n(),
  format = useFormat(),
  route = useRoute(),
  router = useRouter();
const { services, session } = useWorkspace(),
  { busy, error, success, execute } = useFeedback();
const id = route.params.id,
  request = ref(null),
  history = ref([]),
  quotes = ref([]),
  scenario = ref(null),
  simulation = ref(null),
  order = ref(null);
const tab = ref("request"),
  dialog = ref(false),
  nextStatus = ref(""),
  reason = ref("");
const runKey =
  "smartquote.run:" +
  session.value.baseUrl +
  ":" +
  session.value.userId +
  ":" +
  id;
const abort = new AbortController();
async function refresh() {
  const api = services.value;
  const [r, h, q, s] = await Promise.all([
    api.requests.get(id, abort.signal),
    api.requests.history(id, abort.signal),
    session.value.purchasing ? api.quotations.list(id, abort.signal) : [],
    session.value.purchasing
      ? optional(api.evaluations.current(id, abort.signal))
      : null,
  ]);
  request.value = r;
  history.value = h.entries;
  quotes.value = q;
  scenario.value = s;
  const runId =
    new URLSearchParams(window.location.hash.split("?")[1] || "").get(
      "simulation",
    ) || localStorage.getItem(runKey);
  if (runId && session.value.purchasing) {
    simulation.value = await optional(
      api.evaluations.currentSimulation(id, runId, abort.signal),
    );
    order.value = session.value.manager
      ? await optional(api.orders.findBySimulation(runId))
      : null;
  }
}
async function acceptRun(run) {
  simulation.value = await services.value.evaluations.currentSimulation(
    id,
    run.simulationRunId,
  );
  localStorage.setItem(runKey, run.simulationRunId);
  const url = new URL(window.location.href);
  url.hash = "/requests/" + id + "?simulation=" + run.simulationRunId;
  window.history.replaceState(window.history.state, "", url);
  order.value = session.value.manager
    ? await optional(
        services.value.orders.findBySimulation(run.simulationRunId),
      )
    : null;
}
async function updateStatus() {
  await execute(async () => {
    await services.value.requests.changeStatus(
      request.value,
      nextStatus.value,
      reason.value,
    );
    dialog.value = false;
    reason.value = "";
    await refresh();
  }, t("saved"));
}
async function attach(event) {
  const file = event.target.files?.[0];
  if (!file) return;
  await execute(async () => {
    await services.value.requests.attach(request.value, file);
    await refresh();
  }, t("saved"));
  event.target.value = "";
}
onMounted(() => execute(refresh));
onUnmounted(() => abort.abort());
</script>
<template>
  <Button
    :label="t('back')"
    icon="pi pi-arrow-left"
    text
    :disabled="busy"
    @click="router.push('/requests')"
  /><Feedback :error="error" :success="success" />
  <p v-if="!request" class="empty-state" role="status">
    {{ busy ? t("loading") : t("emptyRequests") }}
  </p>
  <template v-else
    ><div class="page-heading">
      <div>
        <p class="eyebrow">{{ t("request") }} · {{ id.slice(0, 8) }}</p>
        <h1>{{ request.title }}</h1>
        <div class="inline-row">
          <Status :value="request.status" /><span class="muted"
            >{{ t("version") }} {{ request.version }} ·
            {{ format.date(request.createdAt) }}</span
          >
        </div>
      </div>
      <div class="inline-row">
        <Button
          :label="t('refresh')"
          icon="pi pi-refresh"
          outlined
          :loading="busy"
          @click="execute(refresh)"
        /><Button
          v-if="session.purchasing && request.nextStatuses.length"
          :label="t('changeStatus')"
          :disabled="busy"
          @click="
            nextStatus = request.nextStatuses[0];
            dialog = true;
          "
        />
      </div>
    </div>
    <ol class="workflow" :aria-label="t('status')">
      <li
        v-for="(step, index) in [
          'Submitted',
          'UnderReview',
          'QuotationCollection',
          'Evaluation',
          'Approved',
          'Ordered',
        ]"
        :key="step"
        :class="{ active: request.status === step }"
        :aria-current="request.status === step ? 'step' : undefined"
      >
        <span>{{ index + 1 }}</span
        >{{ t("statuses." + step) }}
      </li>
    </ol>
    <Tabs v-model:value="tab"
      ><TabList
        ><Tab value="request">{{ t("request") }}</Tab
        ><Tab v-if="session.purchasing" value="quotes"
          >{{ t("quotations") }} ({{ quotes.length }})</Tab
        ><Tab v-if="session.purchasing" value="comparison">{{
          t("comparison")
        }}</Tab
        ><Tab v-if="session.manager" value="order">{{ t("purchaseOrder") }}</Tab
        ><Tab value="history">{{ t("history") }}</Tab></TabList
      ><TabPanels>
        <TabPanel value="request"
          ><div class="detail-grid">
            <section class="panel">
              <h2>{{ t("items") }}</h2>
              <article
                v-for="item in request.items"
                :key="item.itemId"
                class="request-item"
              >
                <div class="section-heading">
                  <h3>{{ item.description }}</h3>
                  <strong>{{ item.quantity }} {{ item.unitOfMeasure }}</strong>
                </div>
                <ul class="requirements">
                  <li v-for="req in item.requirements" :key="req.requirementId">
                    <i class="pi pi-check-circle" />
                    <div>
                      <strong>{{ req.name }}</strong
                      ><span
                        >{{ t("operators." + req.operator) }}
                        {{ req.expectedValue }} {{ req.unitOfMeasure }}</span
                      >
                    </div>
                    <small v-if="req.isMandatory">{{ t("mandatory") }}</small>
                  </li>
                </ul>
              </article>
            </section>
            <aside class="stack">
              <section class="panel">
                <dl>
                  <dt>{{ t("priority") }}</dt>
                  <dd>{{ t("priorities." + request.priority) }}</dd>
                  <dt>{{ t("requiredDate") }}</dt>
                  <dd>{{ format.date(request.requiredDate) }}</dd>
                  <dt>{{ t("requester") }}</dt>
                  <dd class="identifier">{{ request.requesterId }}</dd>
                  <dt>{{ t("updatedAt") }}</dt>
                  <dd>{{ format.date(request.updatedAt, true) }}</dd>
                </dl>
              </section>
              <section class="panel">
                <h2>{{ t("attachments") }}</h2>
                <p class="help-text">{{ t("attachmentHelp") }}</p>
                <p v-if="!request.attachments.length" class="muted">
                  {{ t("emptyAttachments") }}
                </p>
                <ul>
                  <li
                    v-for="file in request.attachments"
                    :key="file.attachmentId"
                  >
                    {{ file.fileName }}
                  </li>
                </ul>
                <Field
                  v-if="session.production"
                  :label="t('attach')"
                  v-slot="{ id: inputId }"
                  ><input
                    :id="inputId"
                    type="file"
                    :disabled="busy"
                    @change="attach"
                /></Field>
              </section>
            </aside></div
        ></TabPanel>
        <TabPanel v-if="session.purchasing" value="quotes"
          ><QuotationPanel
            :request="request"
            :quotes="quotes"
            :busy="busy"
            :execute="execute"
            :refresh="refresh"
        /></TabPanel>
        <TabPanel v-if="session.purchasing" value="comparison"
          ><ComparisonPanel
            :key="scenario?.scenarioId || request.version"
            :request="request"
            :quotes="quotes"
            :scenario="scenario"
            :simulation="simulation"
            :busy="busy"
            :execute="execute"
            :accept-run="acceptRun"
            @scenario="
              (value) => {
                scenario = value;
                if (simulation) simulation.isCurrent = false;
              }
            "
            @order="tab = 'order'"
        /></TabPanel>
        <TabPanel v-if="session.manager" value="order"
          ><OrderPanel
            :request="request"
            :quotes="quotes"
            :simulation="simulation"
            :order="order"
            :busy="busy"
            :execute="execute"
            :refresh="refresh"
            @order="(value) => (order = value)"
        /></TabPanel>
        <TabPanel value="history"
          ><section class="panel">
            <h2>{{ t("history") }}</h2>
            <p v-if="!history.length" class="empty-state">
              {{ t("historyEmpty") }}
            </p>
            <article
              v-for="(entry, index) in history"
              :key="index"
              class="history-entry"
            >
              <i class="pi pi-clock" />
              <div>
                <div class="inline-row">
                  <Status v-if="entry.fromStatus" :value="entry.fromStatus" /><i
                    class="pi pi-arrow-right"
                  /><Status :value="entry.toStatus" />
                </div>
                <p>{{ entry.reason }}</p>
                <small class="muted"
                  >{{ format.date(entry.changedAt, true) }} ·
                  {{ entry.changedBy }}</small
                >
              </div>
            </article>
          </section></TabPanel
        >
      </TabPanels></Tabs
    >
    <Dialog
      v-model:visible="dialog"
      modal
      :header="t('changeStatus')"
      :style="{ width: '32rem' }"
      ><form @submit.prevent="updateStatus" class="stack">
        <Field :label="t('nextStatus')" v-slot="{ id: inputId }"
          ><Select
            :input-id="inputId"
            :aria-label="t('nextStatus')"
            v-model="nextStatus"
            :options="
              request.nextStatuses.map((value) => ({
                value,
                label: t('statuses.' + value),
              }))
            "
            option-label="label"
            option-value="value"
            :disabled="busy" /></Field
        ><Field :label="t('reason')" v-slot="{ id: inputId }"
          ><Textarea
            :id="inputId"
            v-model="reason"
            rows="3"
            required
            :disabled="busy" /></Field
        ><Button
          type="submit"
          :label="t('save')"
          :loading="busy"
        /></form></Dialog
  ></template>
</template>

// components/smartquote/request-detail.tsx
/* oxlint-disable react/react-compiler */
'use client';
import { useCallback, useEffect, useState } from 'react';
import {
  ArrowLeft,
  Check,
  Clock3,
  FileText,
  Paperclip,
  RefreshCw,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { optional, SmartQuoteApi } from '@/lib/smartquote/api';
import type {
  PurchaseOrder,
  PurchaseRequest,
  Quotation,
  RequestHistory,
  Scenario,
  Session,
  Simulation,
} from '@/lib/smartquote/types';
import {
  date,
  flow,
  operators,
  priorities,
  statuses,
  title,
  transitions,
} from '@/lib/smartquote/domain';
import { Choice, ErrorNotice, Field, Loading, Status } from './common';
import { QuotesPanel } from './quotes-panel';
import { ComparisonPanel } from './comparison-panel';
import { OrderPanel } from './order-panel';

export type Action = (
  work: () => Promise<void>,
  success?: string,
) => Promise<void>;
export function RequestDetail({
  id,
  api,
  session,
  onBack,
  onBusy,
}: {
  id: string;
  api: SmartQuoteApi;
  session: Session;
  onBack: () => void;
  onBusy: (v: boolean) => void;
}) {
  const [request, setRequest] = useState<PurchaseRequest | null>(null);
  const [history, setHistory] = useState<RequestHistory | null>(null);
  const [quotes, setQuotes] = useState<Quotation[]>([]);
  const [scenario, setScenario] = useState<Scenario | null>(null);
  const [simulation, setSimulation] = useState<Simulation | null>(null);
  const [order, setOrder] = useState<PurchaseOrder | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [tab, setTab] = useState('request');
  const [dialog, setDialog] = useState(false);
  const [nextStatus, setNextStatus] = useState('');
  const [reason, setReason] = useState('');
  const purchasing = session.roles.some((r) =>
    ['PurchaseAnalyst', 'PurchaseManager'].includes(r),
  );
  const manager = session.roles.includes('PurchaseManager');
  const production = session.roles.includes('ProductionSpecialist');
  const runKey = `smartquote.run:${session.baseUrl}:${session.userId}:${id}`;
  const refresh = useCallback(
    async (signal?: AbortSignal) => {
      const [r, h, q, s] = await Promise.all([
        api.request(id, signal),
        api.history(id, signal),
        purchasing ? api.quotes(id, signal) : Promise.resolve([]),
        purchasing ? optional(api.scenario(id, signal)) : Promise.resolve(null),
      ]);
      if (signal?.aborted) return;
      setRequest(r);
      setHistory(h);
      setQuotes(q);
      setScenario(s);
      const query = new URLSearchParams(window.location.search);
      const runId =
        (query.get('request') === id ? query.get('simulation') : null) ||
        localStorage.getItem(runKey);
      if (runId && purchasing) {
        const run = await optional(api.currentSimulation(id, runId, signal));
        if (run) {
          const ownerScenario = await api.scenarioById(run.scenarioId);
          if (ownerScenario.requestId !== id) {
            localStorage.removeItem(runKey);
            return;
          }
          const foundOrder = manager
            ? await optional(api.orderByRun(runId))
            : null;
          if (!signal?.aborted) {
            setSimulation(run);
            setOrder(foundOrder);
          }
        } else {
          localStorage.removeItem(runKey);
          setSimulation(null);
          setOrder(null);
        }
      }
    },
    [api, id, purchasing, manager, runKey],
  );
  useEffect(() => {
    const abort = new AbortController();
    refresh(abort.signal).catch((e) => {
      if (!abort.signal.aborted) setError(e.message);
    });
    return () => abort.abort();
  }, [refresh]);
  const action: Action = async (work, message) => {
    setBusy(true);
    onBusy(true);
    setError('');
    setSuccess('');
    try {
      await work();
      if (message) setSuccess(message);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
      onBusy(false);
    }
  };
  async function updateStatus(e: React.SyntheticEvent) {
    e.preventDefault();
    if (!request) return;
    await action(async () => {
      await api.changeStatus(request, nextStatus, reason);
      setDialog(false);
      setReason('');
      await refresh();
    }, 'Estado actualizado.');
  }
  async function acceptRun(run: Simulation) {
    const s = await api.scenarioById(run.scenarioId);
    if (s.requestId !== id)
      throw new Error('La simulación pertenece a otra solicitud.');
    localStorage.setItem(runKey, run.simulationRunId);
    setSimulation(await api.currentSimulation(id, run.simulationRunId));
    window.history.replaceState(
      null,
      '',
      '?' +
        new URLSearchParams({ request: id, simulation: run.simulationRunId }),
    );
    setOrder(
      manager ? await optional(api.orderByRun(run.simulationRunId)) : null,
    );
  }
  if (!request)
    return (
      <>
        <Button variant="ghost" onClick={onBack}>
          <ArrowLeft />
          Volver
        </Button>
        <ErrorNotice message={error} />
        {!error && <Loading />}
      </>
    );
  return (
    <>
      <div className="detail-top">
        <Button variant="ghost" onClick={onBack} disabled={busy}>
          <ArrowLeft />
          Solicitudes
        </Button>
        <Button
          variant="outline"
          onClick={() => action(() => refresh())}
          disabled={busy}
        >
          <RefreshCw />
          Actualizar
        </Button>
      </div>
      <div className="page-heading">
        <div>
          <span className="eyebrow">
            SOLICITUD · {request.requestId.slice(0, 8)}
          </span>
          <h1>{title(request)}</h1>
          <div className="inline-row">
            <Status value={request.status} />
            <span className={`priority priority-${request.priority}`}>
              {priorities[request.priority]}
            </span>
            <span className="muted">
              Requerido: {date(request.requiredDate)}
            </span>
          </div>
        </div>
        {purchasing && (transitions[request.status]?.length ?? 0) > 0 && (
          <Button
            variant="outline"
            disabled={busy}
            onClick={() => {
              setNextStatus(transitions[request.status][0]);
              setDialog(true);
            }}
          >
            Cambiar estado
          </Button>
        )}
      </div>
      <div className="workflow" aria-label="Avance de solicitud">
        {flow.map((step, index) => (
          <div
            key={step}
            className={
              index <= flow.indexOf(request.status)
                ? 'flow-step reached'
                : 'flow-step'
            }
          >
            <span>
              {index < flow.indexOf(request.status) ? <Check /> : index + 1}
            </span>
            <label>{statuses[step]}</label>
          </div>
        ))}
      </div>
      <ErrorNotice message={error} />
      {success && (
        <output className="success-notice">
          <Check />
          {success}
        </output>
      )}
      {busy && (
        <output className="busy-line">
          Guardando y verificando con la API…
        </output>
      )}
      <Tabs value={tab} onValueChange={(v) => setTab(String(v))}>
        <TabsList variant="line" className="detail-tabs">
          <TabsTrigger value="request">Solicitud</TabsTrigger>
          {purchasing && (
            <>
              <TabsTrigger value="quotes">
                Cotizaciones <span className="count">{quotes.length}</span>
              </TabsTrigger>
              <TabsTrigger value="comparison">Comparación</TabsTrigger>
              <TabsTrigger value="order">Orden de compra</TabsTrigger>
            </>
          )}
          <TabsTrigger value="history">Historial</TabsTrigger>
        </TabsList>
        <TabsContent value="request">
          <div className="detail-grid">
            <section>
              <div className="section-heading">
                <h2>Insumos solicitados</h2>
                <span className="muted">{request.items.length} ítems</span>
              </div>
              {request.items.map((item) => (
                <article className="panel requested-item" key={item.itemId}>
                  <div className="section-heading">
                    <div>
                      <span className="eyebrow">INSUMO {item.lineNumber}</span>
                      <h3>{item.description}</h3>
                    </div>
                    <span className="quantity">
                      {item.quantity.toLocaleString('es-PE')}{' '}
                      <small>{item.unitOfMeasure}</small>
                    </span>
                  </div>
                  <div className="requirements">
                    {item.requirements.map((r) => (
                      <div key={r.requirementId} className="requirement-row">
                        <div>
                          <strong>{r.name}</strong>
                          <span>
                            {operators[r.operator]} {r.expectedValue}{' '}
                            {r.unitOfMeasure}
                          </span>
                        </div>
                        <span className={r.isMandatory ? 'mandatory' : 'muted'}>
                          {r.isMandatory ? 'Obligatorio' : 'Referencial'}
                        </span>
                      </div>
                    ))}
                  </div>
                </article>
              ))}
            </section>
            <aside>
              <div className="panel">
                <h3>Datos de la solicitud</h3>
                <dl className="facts">
                  <div>
                    <dt>Registrada</dt>
                    <dd>{date(request.createdAt)}</dd>
                  </div>
                  <div>
                    <dt>Próxima área responsable</dt>
                    <dd>{request.nextResponsibleArea}</dd>
                  </div>
                  <div>
                    <dt>Identificador</dt>
                    <dd className="id-value">{request.requestId}</dd>
                  </div>
                </dl>
              </div>
              <div className="panel">
                <h3>
                  <Paperclip />
                  Sustento técnico
                </h3>
                {request.attachments.length ? (
                  request.attachments.map((a) => (
                    <div className="attachment" key={a.attachmentId}>
                      <FileText />
                      <div>
                        {a.fileName}
                        <small>{date(a.uploadedAt)}</small>
                      </div>
                    </div>
                  ))
                ) : (
                  <p className="muted">Sin archivos adjuntos.</p>
                )}
                {production && (
                  <Field label="Adjuntar documento (máximo 10 MB)">
                    <Input
                      aria-label="Sustento técnico"
                      type="file"
                      disabled={busy}
                      accept=".pdf,.png,.jpg,.jpeg"
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (!file) return;
                        e.target.value = '';
                        void action(async () => {
                          if (!file.size || file.size > 10 * 1024 * 1024)
                            throw new Error(
                              'El archivo debe contener entre 1 byte y 10 MB.',
                            );
                          await api.attach(request, file);
                          await refresh();
                        }, 'Sustento adjuntado.');
                      }}
                    />
                  </Field>
                )}
                <small className="muted">
                  La API actual registra los adjuntos; todavía no permite
                  descargarlos.
                </small>
              </div>
            </aside>
          </div>
        </TabsContent>
        <TabsContent value="quotes">
          <QuotesPanel
            api={api}
            request={request}
            quotes={quotes}
            busy={busy}
            action={action}
            refresh={refresh}
          />
        </TabsContent>
        <TabsContent value="comparison">
          <ComparisonPanel
            key={scenario?.scenarioId ?? request.version}
            api={api}
            request={request}
            quotes={quotes}
            scenario={scenario}
            simulation={simulation}
            busy={busy}
            action={action}
            onScenario={(s) => {
              setScenario(s);
              if (simulation)
                setSimulation({ ...simulation, isCurrent: false });
            }}
            onSimulation={acceptRun}
            onReviewOrder={() => setTab('order')}
          />
        </TabsContent>
        <TabsContent value="order">
          <OrderPanel
            api={api}
            request={request}
            quotes={quotes}
            simulation={simulation}
            order={order}
            manager={manager}
            busy={busy}
            action={action}
            onOrder={setOrder}
            refresh={refresh}
          />
        </TabsContent>
        <TabsContent value="history">
          <section className="panel">
            <h2>Historial de cambios</h2>
            <ol className="timeline">
              {history?.entries.map((entry, index) => (
                <li key={entry.changedAt + index}>
                  <span className="timeline-dot">
                    <Clock3 />
                  </span>
                  <div>
                    <div className="inline-row">
                      <Status value={entry.toStatus} />
                      <span className="muted">
                        {date(entry.changedAt, true)}
                      </span>
                    </div>
                    <p>{entry.reason}</p>
                    <small className="muted">
                      Responsable: {entry.changedBy}
                    </small>
                  </div>
                </li>
              ))}
            </ol>
          </section>
        </TabsContent>
      </Tabs>
      <Dialog
        open={dialog}
        onOpenChange={(value) => {
          if (!busy) setDialog(value);
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Cambiar estado de solicitud</DialogTitle>
            <DialogDescription>
              El cambio se registrará en el historial y notificará al
              solicitante.
            </DialogDescription>
          </DialogHeader>
          <form onSubmit={updateStatus}>
            <Field label="Nuevo estado">
              <Choice
                label="Nuevo estado"
                value={nextStatus}
                onChange={setNextStatus}
                options={Object.fromEntries(
                  (transitions[request.status] ?? []).map((v) => [
                    v,
                    statuses[v],
                  ]),
                )}
                disabled={busy}
              />
            </Field>
            <Field label="Motivo">
              <Textarea
                required
                value={reason}
                onChange={(e) => setReason(e.target.value)}
                disabled={busy}
              />
            </Field>
            <ErrorNotice message={error} />
            <Button type="submit" disabled={busy || !reason.trim()}>
              Guardar cambio
            </Button>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
}
